# Generated by Django 5.0.3 on 2024-05-05 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                ("tc", models.BooleanField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BugOrganization",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("org_name", models.CharField(max_length=100)),
                ("org_email", models.EmailField(max_length=254)),
                ("org_password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserCreationMethod",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BugOrganizationDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("org_country", models.CharField(max_length=50)),
                ("org_city", models.CharField(max_length=50)),
                ("org_address", models.TextField()),
                ("org_phone", models.CharField(max_length=15)),
                ("org_profile_pic", models.ImageField(upload_to="org_profile_pics/")),
                ("org_website", models.CharField(max_length=100)),
                ("org_description", models.TextField()),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buguser.bugorganization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BugUserDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("country", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=15)),
                ("profile_pic", models.ImageField(upload_to="profile_pics/")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BugUserSession",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="created_via",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="buguser.usercreationmethod",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="buguser.usertype",
            ),
        ),
    ]
