# Generated by Django 5.0.3 on 2024-07-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buguser", "0004_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="buguserdetail",
            name="about_me",
            field=models.TextField(blank=True, null=True),
        ),
    ]
