# Generated by Django 5.0.3 on 2024-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buguser", "0005_buguserdetail_about_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="buguserdetail",
            name="position",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
