# Generated by Django 5.0.3 on 2024-07-16 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buguser", "0006_buguserdetail_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugUserEducation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("school_name", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                ("field_of_study", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
