# Generated by Django 5.0.3 on 2024-09-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buguser", "0007_bugusereducation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buguserskill",
            name="skill_level",
        ),
    ]
