# Generated by Django 5.0.3 on 2024-09-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buguser", "0008_remove_buguserskill_skill_level"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bugbearskill",
            old_name="skill_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="bugbearskill",
            old_name="skill_logo",
            new_name="logo",
        ),
        migrations.RenameField(
            model_name="bugbearskill",
            old_name="skill_name",
            new_name="name",
        ),
    ]
