# Generated by Django 5.0.3 on 2024-09-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buguser", "0010_remove_bugorganizationdetail_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugorganizationdetail",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="organization_pics/"
            ),
        ),
    ]
