# Generated by Django 5.0.3 on 2024-09-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buguser", "0011_bugorganizationdetail_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugorganizationdetail",
            name="about_company",
            field=models.TextField(blank=True, null=True),
        ),
    ]
