# Generated by Django 5.0.3 on 2024-09-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buguser", "0012_bugorganizationdetail_about_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugorganizationdetail",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
    ]
