# Generated by Django 5.0.3 on 2024-12-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buguser", "0013_bugorganizationdetail_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
