# Generated by Django 5.0.3 on 2025-01-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_name_comment_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="title",
        ),
    ]
