# Generated by Django 5.0.3 on 2024-09-03 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buguser", "0007_bugusereducation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BugJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("responsibilities", models.TextField()),
                ("job_posted", models.DateField()),
                ("job_expiry", models.DateField()),
                ("salary_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salary_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("location", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part Time"),
                            ("Contract", "Contract"),
                            ("Internship", "Internship"),
                        ],
                        default="Full Time",
                        max_length=50,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("0-2 Years", "0-2 Years"),
                            ("3-5 Years", "3-5 Years"),
                            ("6-9 Years", "6-9 Years"),
                            ("10-15 Years", "10-15 Years"),
                            ("15+ Years", "15+ Years"),
                        ],
                        max_length=50,
                    ),
                ),
                ("education", models.CharField(default="Graduation", max_length=255)),
                ("featured", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="buguser.bugorganization",
                    ),
                ),
            ],
        ),
    ]
