# Generated by Django 5.0.3 on 2024-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bugjob",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
