# Generated by Django 5.0.3 on 2024-09-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_bugjob_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugjob",
            name="job_description",
        ),
        migrations.AddField(
            model_name="bugjob",
            name="qualifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bugjob",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bugjob",
            name="responsibilities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
