# Generated by Django 5.0.3 on 2024-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_remove_bugjob_job_description_bugjob_qualifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bugjob",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
