# Generated by Django 5.0.3 on 2024-09-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_bugjob_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobsapplied",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
