# Generated by Django 5.0.3 on 2024-06-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseorder",
            name="modules",
        ),
    ]
